### ISSUE TITLE
Change namespacing

### ISSUE THREAD

**Issue by alepore** [spree-contrib/spree_globalize#16]
We already discussed this.. but i still think we should change `Spree::Globalize` to `SpreeGlobalize`.
I like the first but that's inconsistent with every other spree extension, i18n included.

From the readme:
```
SpreeI18n::Config.available_locales = [:en, :es, :'pt-BR'] 
Spree::Globalize::Config.supported_locales = [:en, :'pt-BR']
```

/cc @tvdeyen

**Comment by tvdeyen** [comment]
For me both are ok. I also prefer the first one, because it feels more "right". But I also see the downsides because of the potential conflict with the top level `Globalize` constant.

What are the reasons you want to change the namespace @alepore ?

**Comment by alepore** [comment]
@tvdeyen just because *all* the spree-contrib extensions are already `SpreeSomething`, and that's also what the spree extension generator does.

**Comment by tvdeyen** [comment]
Since this should be non breaking I would say: Go for it. Should I or will you prepare a pull request?

**Comment by alepore** [comment]
@tvdeyen i'm taking a look at it

**Comment by tvdeyen** [comment]
Mille grazie! 💥
