### ISSUE TITLE
N+1 queries

### ISSUE THREAD

**Issue by alepore** [spree-contrib/spree_globalize#3]
This was discussed and fixed here https://github.com/spree-contrib/spree_i18n/issues/418, than reverted here https://github.com/spree-contrib/spree_i18n/issues/478 .

Still a big performance problem, we should find a way to use `with_translation`, `includes(:translations)` or whatever

/cc @hnatt @BlackPrincess

**Comment by alepore** [comment]
what about adding a `default_spree_scopes` scope to all model, with a safe/empty default (`all` should work)?
those default scopes will not be automagically applied everywhere but we can add it on all main queries and encourage its use.
and extension (like spree_globalize) can add important things, in this case `includes(:translations).references(:translations)`

**Comment by imgarylai** [comment]
Would this issue be reopened? It is still an issue for multiple lang site.
